// resources/js/Pages/WordProcessor.vue
<script setup lang="ts">
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm } from '@inertiajs/vue3';

const form = useForm('formData', {
    words: '',
});

const submit = () => {
    form.post(route('word-processor.store'), {
        onFinish: () => {
            console.log('finished, should have cleared');
            form.reset('words');
        },
    });
};
</script>
<template>
    <Head title="Word Processor" />
    <AuthenticatedLayout>
        <template #header>
            <h2
                class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200"
            >
                Word Processor
            </h2>
        </template>
        <form @submit.prevent="submit" class="bg-slate-300 p-4">
            <!-- cards bg -->
            <div class="flex items-start justify-between">
                <div class="my-4 h-[20rem] w-2/4">
                    <InputLabel for="words" value="Words" />
                    <!-- <TextInput
                    id="words"
                    type="text"
                    class="mt-1 block w-full"
                    v-model="form.words"
                    required
                    autofocus
                    autocomplete="words"
                /> -->

                    <textarea
                        name="words"
                        id="words"
                        class="h-full w-full p-2"
                        v-model="form.words"
                        autocomplete="words"
                        required
                    ></textarea>

                    <InputError class="mt-2" :message="form.errors.words" />
                </div>

                <div class="border p-2">OR Upload your file</div>
            </div>

            <PrimaryButton>Submit</PrimaryButton>
        </form>
    </AuthenticatedLayout>
</template>

// resources/js/pages/word-processor.tsx
import InputError from '@/components/input-error';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import AppLayout from '@/layouts/app-layout';
import { BreadcrumbItem } from '@/types';
import { Head, useForm } from '@inertiajs/react';
import { FormEventHandler } from 'react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Word Processor',
        href: '/word-processor',
    },
];

type WordsForm = {
    words: string;
};

export default function WordProcessor() {
    const { data, setData, post, processing, errors, reset } = useForm<Required<WordsForm>>({
        words: '',
    });

    const submit: FormEventHandler = (e) => {
        e.preventDefault();

        post(route('word-processor.store'), {
            onFinish: () => {
                console.log('finished, should have cleared');
                reset('words');
            },
        });
    };
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Word Processor" />
            {/* <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4"></div> */}

            <form className="flex flex-col gap-6" onSubmit={submit}>
                <div className="grid gap-6">
                    <Label htmlFor="words">Words</Label>
                    {/* <Input
                        id="name"
                        type="text"
                        required
                        autoFocus
                        tabIndex={1}
                        autoComplete="name"
                        value={data.name}
                        onChange={(e) => setData('name', e.target.value)}
                        disabled={processing}
                        placeholder="Full name"
                    /> */}
                    <Textarea placeholder="Put your words here" />
                    <InputError message={errors.words} className="mt-2" />
                </div>
            </form>
        </AppLayout>
    );
}
